---
    - name: collecting server pub ip
      uri:
        url: http://169.254.169.254/latest/meta-data/public-ipv4
        return_content: yes
      register: myipaddress

    - name: Assigning public ipaddress
      set_fact: pub_ip="{{myipaddress.content}}"

    - name: Installing apache
      yum:
        name: httpd
        state: present

    - name: Enabling httpd service
      service:
        name: httpd
        enabled: yes

    - name: Copying index.html file
      template:
        src: index.html
        dest: /var/www/html/
      notify: apache restart

    - name: modifying httpd.conf file
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^#ServerName www.example.com'
